services:
  envoy:
    image: envoyproxy/envoy-dev:latest
    container_name: envoy-proxy
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
