services:
  # app:
  #   build: .
  #   container_name: golang-app
  #   depends_on:
  #     - envoy

  envoy:
    image: envoyproxy/envoy-dev:latest
    container_name: envoy-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./configs/envoy.yaml:/etc/envoy/envoy.yaml
